name: preservedtopersevere
favicon: null
layout_spectrum: 0.8335637990385294
typography_spectrum: 0.03749736025929451
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.18925600871443748
  lightness: 0.2736637652851641
  saturation: 0.9818216843996197
  rhythmicContrast: 0.13704605540260673
purpose: []
